In [1]:
import treecorr
import pyccl as ccl
import numpy as np
filename = '/global/homes/j/jharno/IA-infusion/SkySim5000/GalCat/StageIV_nz/GalCat_tomo1_All_0.06GpAM_RA_Dec_g1_g2_w_den_Sij.dat'
config = { 'ra_col' : 1,
           'dec_col' : 2,
           'g1_col' : 3,
           'g2_col' : 4,
           'w_col' : 5,
           'ra_units' : 'deg',
           'dec_units' : 'deg' }
#cat = treecorr.Catalog(filename, config)  ##This doesn't allow us to add the distances directly since we have to convert those from the z_true using ccl first
cosmo = ccl.Cosmology(Omega_c = 0.22, 
                      h = 0.71,
                      Omega_b = 0.0448,
                      n_s = 0.963,
                      sigma8 = 0.801,
                      Omega_k = 0.0,
                      w0 = -1.00,
                      #Omega_nu = 0.0
                      wa = 0.0,)

In [2]:
data = np.loadtxt(filename)
ra = data[:,0]
dec = data[:,1]
g1 = data[:,2]
g2 = data[:,3]
w = data[:,4]
z = data[:,5]
r = ccl.comoving_radial_distance(cosmo, 1./(1+z))
cat = treecorr.Catalog(ra = ra, dec=dec, g1=g1, g2=g2, w=w, r=r, ra_units='degrees', dec_units='degrees')



In [19]:
gg = treecorr.GGCorrelation(nbins = 9,
                       min_sep = 0.00833333, #0.5 arcmin
                       max_sep = 7.925, #475.5 arcmin
                       bin_slop = 0.01) 

In [13]:
gg.process(cat, metric = 'Rperp')

In [15]:
gg.xip

array([2.04216917e-06, 3.17183454e-06, 3.04377876e-06, 2.98986691e-06,
       2.25493490e-06, 1.58498188e-06, 9.75605654e-07, 5.25226026e-07,
       2.56555993e-07])

In [16]:
gg.xim

array([ 2.90049880e-07, -1.24550796e-07, -1.68422636e-07,  7.23098282e-08,
       -1.91173046e-09,  4.45568920e-10, -9.30595704e-09, -7.43834750e-10,
       -1.33638437e-10])

In [18]:
gg.npairs

array([1.19200000e+03, 5.41000000e+03, 2.46990000e+04, 1.13663000e+05,
       5.19442000e+05, 2.37748900e+06, 1.08604670e+07, 4.93122490e+07,
       2.21077707e+08])